name: Test CI/CD Pipeline v2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pytest tests/unit

  deploy:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      run: |
        docker login ${{ secrets.AZURE_ACR_USERNAME }}.azurecr.io -u ${{ secrets.AZURE_ACR_USERNAME }} -p ${{ secrets.AZURE_ACR_PASSWORD }}
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.AZURE_ACR_USERNAME }}.azurecr.io/myfunctionapp:latest -f Dockerfile .
        docker push ${{ secrets.AZURE_ACR_USERNAME }}.azurecr.io/myfunctionapp:latest